name: Deploy Worker
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Copy .env
              run: cp .env.example .env

            - name: Install deps
              run: pnpm i

            - name: Deploy
              run: pnpm run deploy
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
